[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
num = { version = "0.4.3", features = ["serde"] }
scilib = "1.0.0"
serde = "1.0.228"
serde-pickle = "1.2.0"
serde_derive = "1.0.228"
